name: RubyFreedomMod
main: me.totalfreedom.totalfreedommod.TotalFreedomMod
version: ${tfm.build.version}
description: Plugin for the Ruby Freedom server.
depend: [Aero, WorldEdit]
softdepend: [BukkitTelnet, Essentials]
authors: [Madgeek1450, Prozza, phoenixpug]

# plugin.yml is no longer used to define commands.
